-- Developed by: Matt Mitchell
-- Date: 05/27/2021

INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('1', 'AFA', 'Afghani');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('2', 'DZD', 'Algerian Dinar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('3', 'ARS', 'Argentine Peso');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('4', 'AMD', 'Armenian Dram');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('5', 'AWG', 'Aruban Guilder');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('6', 'AUD', 'Australian Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('7', 'AZM', 'Azerbaijanian Manat');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('8', 'BSD', 'Bahamian Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('9', 'BHD', 'Bahraini Dinar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('10', 'THB', 'Baht');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('11', 'PAB', 'Balboa');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('12', 'BBD', 'Barbados Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('13', 'BEF', 'Belgian Franc');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('14', 'VEB', 'Bolivar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('15', 'BOB', 'Boliviano');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('16', 'BRL', 'Brazilian Real');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('17', 'BND', 'Brunei Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('18', 'BGN', 'Bulgarian Lev');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('19', 'CAD', 'Canadian Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('20', 'GHC', 'Cedi');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('21', 'XOF', 'CFA Franc BCEAO');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('22', 'CLP', 'Chilean Peso');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('23', 'COP', 'Colombian Peso');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('24', 'CRC', 'Costa Rican Colon');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('25', 'HRK', 'Croatian Kuna');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('26', 'CYP', 'Cyprus Pound');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('27', 'CZK', 'Czech Koruna');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('28', 'DKK', 'Danish Krone');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('29', 'DEM', 'Deutsche Mark');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('30', 'DOP', 'Dominican Peso');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('31', 'VND', 'Dong');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('32', 'GRD', 'Drachma');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('33', 'EGP', 'Egyptian Pound');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('34', 'SVC', 'El Salvador Colon');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('35', 'AED', 'Emirati Dirham');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('36', 'EUR', 'EURO');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('37', 'FJD', 'Fiji Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('38', 'HUF', 'Forint');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('39', 'FRF', 'French Franc');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('40', 'PYG', 'Guarani');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('41', 'HKD', 'Hong Kong Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('42', 'ISK', 'Iceland Krona');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('43', 'INR', 'Indian Rupee');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('44', 'IEP', 'Irish Pound');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('45', 'ITL', 'Italian Lira');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('46', 'JMD', 'Jamaican Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('47', 'JOD', 'Jordanian Dinar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('48', 'KES', 'Kenyan Shilling');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('49', 'EEK', 'Kroon');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('50', 'KWD', 'Kuwaiti Dinar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('51', 'AOA', 'Kwanza');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('52', 'LVL', 'Latvian Lats');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('53', 'LBP', 'Lebanese Pound');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('54', 'ALL', 'Lek');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('55', 'ROL', 'Leu');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('56', 'LTL', 'Lithuanian Litas');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('57', 'MYR', 'Malaysian Ringgit');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('58', 'MTL', 'Maltese Lira');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('59', 'FIM', 'Markka');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('60', 'MUR', 'Mauritius Rupee');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('61', 'MXN', 'Mexican Peso');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('62', 'MAD', 'Moroccan Dirham');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('63', 'NGN', 'Naira');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('64', 'NAD', 'Namibia Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('65', 'NPR', 'Nepalese Rupee');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('66', 'ANG', 'Netherlands Antillian Guilder');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('67', 'NLG', 'Netherlands Guilder');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('68', 'ILS', 'New Israeli Shekel');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('69', 'TWD', 'New Taiwan Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('70', 'NZD', 'New Zealand Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('71', 'BTN', 'Ngultrum');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('72', 'NOK', 'Norwegian Krone');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('73', 'PEN', 'Nuevo Sol');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('74', 'OMR', 'Omani Rial');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('75', 'PKR', 'Pakistan Rupee');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('76', 'PHP', 'Philippine Peso');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('77', 'PLZ', 'Polish Zloty(old)');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('78', 'PTE', 'Portuguese Escudo');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('79', 'GTQ', 'Quetzal');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('80', 'ZAR', 'Rand');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('81', 'MVR', 'Rufiyaa');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('82', 'IDR', 'Rupiah');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('83', 'RUB', 'Russian Ruble');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('84', 'RUR', 'Russian Ruble(old)');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('85', 'SAR', 'Saudi Riyal');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('86', 'ATS', 'Shilling');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('87', 'SGD', 'Singapore Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('88', 'SKK', 'Slovak Koruna');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('89', 'ESP', 'Spanish Peseta');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('90', 'LKR', 'Sri Lankan Rupee');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('91', 'SEK', 'Swedish Krona');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('92', 'CHF', 'Swiss Franc');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('93', 'BDT', 'Taka');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('94', 'SIT', 'Tolar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('95', 'TTD', 'Trinidad and Tobago Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('96', 'TND', 'Tunisian Dinar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('97', 'TRL', 'Turkish Lira');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('98', 'GBP', 'United Kingdom Pound');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('99', 'UYU', 'Uruguayan Peso');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('100', 'USD', 'US Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('101', 'KRW', 'Won');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('102', 'JPY', 'Yen');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('103', 'CNY', 'Yuan Renminbi');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('104', 'ZWD', 'Zimbabwe Dollar');
INSERT INTO AdventureWorksDW.dimCurrency (CurrencyKeyID, CurrencyAlternateKeyID, CurrencyName) VALUES ('105', 'PLN', 'Zloty');