-- Developed by: Matt Mitchell
-- Date: 09/27/2018

INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('1', '1', 'No Discount', 'Sin descuento', 'Aucune remise', '0', 'No Discount', 'Sin descuento', 'Aucune remise', 'No Discount', 'Sin descuento', 'Aucune remise', '2010/11/29', '2014/6/30', '0', '0');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('2', '2', 'Volume Discount 11 to 14', 'Descuento por volumen (entre 11 y 14)', 'Remise sur quantité (de 11 à 14)', '0.02', 'Volume Discount', 'Descuento por volumen', 'Remise sur quantité', 'Reseller', 'Distribuidor', 'Revendeur', '2010/12/29', '2013/12/28', '11', '14');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('3', '3', 'Volume Discount 15 to 24', 'Descuento por volumen (entre 15 y 24)', 'Remise sur quantité (de 15 à 24)', '0.05', 'Volume Discount', 'Descuento por volumen', 'Remise sur quantité', 'Reseller', 'Distribuidor', 'Revendeur', '2010/12/29', '2013/12/28', '15', '24');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('4', '4', 'Volume Discount 25 to 40', 'Descuento por volumen (entre 25 y 40)', 'Remise sur quantité (de 25 à 40)', '0.1', 'Volume Discount', 'Descuento por volumen', 'Remise sur quantité', 'Reseller', 'Distribuidor', 'Revendeur', '2010/12/29', '2013/12/28', '25', '40');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('5', '5', 'Volume Discount 41 to 60', 'Descuento por volumen (entre 41 y 60)', 'Remise sur quantité (de 41 à 60)', '0.149999999999999', 'Volume Discount', 'Descuento por volumen', 'Remise sur quantité', 'Reseller', 'Distribuidor', 'Revendeur', '2010/12/29', '2013/12/28', '41', '60');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('6', '6', 'Volume Discount over 60', 'Descuento por volumen (más de 60)', 'Remise sur quantité (au-delà de 60)', '0.2', 'Volume Discount', 'Descuento por volumen', 'Remise sur quantité', 'Reseller', 'Distribuidor', 'Revendeur', '2010/12/29', '2013/12/28', '61', '61');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('7', '7', 'Mountain-100 Clearance Sale', 'Liquidación de bicicleta de montaña, 100', 'Liquidation VTT 100', '0.349999999999999', 'Discontinued Product', 'Descatalogado', 'Ce produit n''est plus commercialisé', 'Reseller', 'Distribuidor', 'Revendeur', '2011/11/12', '2011/12/28', '0', '0');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('8', '8', 'Sport Helmet Discount-2002', 'Casco deportivo, descuento: 2002', 'Remise sur les casques sport - 2002', '0.1', 'Seasonal Discount', 'Descuento de temporada', 'Remise saisonnière', 'Reseller', 'Distribuidor', 'Revendeur', '2011/12/29', '2012/1/28', '0', '0');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('9', '9', 'Road-650 Overstock', 'Bicicleta de carretera: 650, oferta especial', 'Déstockage Vélo de route 650', '0.299999999999999', 'Excess Inventory', 'Inventario excedente', 'Déstockage', 'Reseller', 'Distribuidor', 'Revendeur', '2011/12/29', '2012/2/28', '0', '0');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('10', '10', 'Mountain Tire Sale', 'Oferta de cubierta de montaña', 'Vente de pneus de VTT', '0.5', 'Excess Inventory', 'Inventario excedente', 'Déstockage', 'Customer', 'Cliente', 'Client', '2012/12/12', '2013/2/26', '0', '0');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('11', '11', 'Sport Helmet Discount-2003', 'Casco deportivo, descuento: 2003', 'Remise sur les casques sport - 2003', '0.149999999999999', 'Seasonal Discount', 'Descuento de temporada', 'Remise saisonnière', 'Reseller', 'Distribuidor', 'Revendeur', '2012/12/28', '2013/1/27', '0', '0');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('12', '12', 'LL Road Frame Sale', 'Oferta de cuadro de carretera GB', 'Vente de cadres de vélo de route LL', '0.349999999999999', 'Excess Inventory', 'Inventario excedente', 'Déstockage', 'Reseller', 'Distribuidor', 'Revendeur', '2012/12/28', '2013/2/11', '0', '0');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('13', '13', 'Touring-3000 Promotion', 'Promoción ‘Touring-3000’', 'Promotion “Touring-3000”', '0.149999999999999', 'New Product', 'Producto Nuevo', 'Nouveau produit', 'Reseller', 'Distribuidor', 'Revendeur', '2012/12/28', '2013/3/29', '0', '0');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('14', '14', 'Touring-1000 Promotion', 'Promoción ‘Touring-1000’', 'Promotion “Touring-1000”', '0.2', 'New Product', 'Producto Nuevo', 'Nouveau produit', 'Reseller', 'Distribuidor', 'Revendeur', '2012/12/28', '2013/3/29', '0', '0');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('15', '15', 'Half-Price Pedal Sale', 'Venta de pedales a mitad de precio', 'Pédales à moitié prix', '0.5', 'Seasonal Discount', 'Descuento de temporada', 'Remise saisonnière', 'Customer', 'Cliente', 'Client', '2013/2/11', '2013/3/14', '0', '0');
INSERT INTO AdventureWorksDW.dimPromotion (PromotionKeyID, PromotionAlternateKeyID, EnglishPromotionName, SpanishPromotionName, FrenchPromotionName, DiscountPct, EnglishPromotionType, SpanishPromotionType, FrenchPromotionType, EnglishPromotionCategory, SpanishPromotionCategory, FrenchPromotionCategory, StartDate, EndDate, MinQty, MaxQty) VALUES ('16', '16', 'Mountain-500 Silver Clearance Sale', 'Liquidación de bicicleta de montaña, 500, plateada', 'Liquidation VTT 500 argent', '0.4', 'Discontinued Product', 'Descatalogado', 'Ce produit n''est plus commercialisé', 'Reseller', 'Distribuidor', 'Revendeur', '2013/10/29', '2013/12/28', '0', '0');
